---

# Author: Christian Claus

- name: Provision webservers
  hosts: webservers
  gather_facts: True
  serial: 2
  roles:
    - base-packages
    - shell-settings
  tasks:
  - name: Ensure nginx is installed
    apt:
      name: nginx
      state: present
      update_cache: yes
  - name: Ensure nginx is started and enabled to start at boot
    service: 
      name: nginx 
      state: started 
      enabled: yes      
  - name: Template index page
    template:
      src: templates/index.html.j2
      dest: /var/www/html/index.nginx-debian.html

